### PR TITLE
Add EncodeBytes

### PR DESCRIPTION
**Pull request by lherman-cs**
Allow encode byte slice. This API can be useful for encoding raw data where we don't want to make a full copy to just convert the slice type, e.g. audio from file.

### CODE REVIEW

**Comment by hraban** [comment]
Hi @lherman-cs thanks for this PR. One question that immediately comes to mind while reading this: how would you ensure byte order of the file? You're casting a `*uint8` to either a float or int16 array; I think this is undefined behaviour. Just because it's happening in C and the compiler doesn't catch it (because you're doing the cast) doesn't make it valid, unless you originally obtained that pointer from an area of memory that was, itself, the same type.

Is there a way to read the original files as a float array or int8 array? I'm not very comfortable adding this API.

**Comment by hraban** [comment]
Additionally, if you're comfortable with this typecast, I think you can do this user-side by using unsafe and casting twice. I don't want to block your use case necessarily, so if you think your array is a valid in-memory representation of an int16 one for example (you'd have to check byte order at the very least), then perhaps you can try that?

**Comment by lherman-cs** [comment]
> Hi @lherman-cs thanks for this PR. One question that immediately comes to mind while reading this: how would you ensure byte order of the file? You're casting a `*uint8` to either a float or int16 array; I think this is undefined behaviour. Just because it's happening in C and the compiler doesn't catch it (because you're doing the cast) doesn't make it valid, unless you originally obtained that pointer from an area of memory that was, itself, the same type.
> 
> Is there a way to read the original files as a float array or int8 array? I'm not very comfortable adding this API.

I think the expectation is that the byte order is always going to be the host byte order. The other APIs, Encode and EncodeFloat32, have the same problems, int16/float32 can contain any byte order. 

Unfortunately, my case is slightly more complex since I have to deal with different platforms, where the APIs can be varied. Here's the link to the project, https://github.com/pion/mediadevices.

I'm okay doing the unsafe.Pointer in the user side. I just figured that it would be useful for other people. Thanks!

**Comment by hraban** [comment]
> The other APIs, Encode and EncodeFloat32, have the same problems, int16/float32 can contain any byte order.

I'm afraid this isn't true. int16 and float32 are explicitly an abstraction layer above bytes: they are an abstract concept, computers just happen to _store_ them as bytes. What you are doing here is implicitly decoding a stream of bytes into a stream of ints. Note that the libopus API doesn't deal in bytes; it deals in int16s or float32s. How you get those is up to you; could be bytes, could be written on a piece of paper, could be JSON arrays directly parsed. Encoding and decoding a stream of int16s / float32s into bytes and back is up to you, the user.

The question is: where did you get those bytes? libopus also doesn't _output_ bytes (again it outputs int16s and float32s) so something, somewhere, did the transformation to bytes. Where did that happen? Where did you get this data? If that typecast happened in the same host as you are doing this on, you can safely cast it back. If you are reading from a .wav file, you need a wav reader library which will return int16[]. Note that wav is a format for encoding an array of int16 (or int32) values into bytes, and back. Once you have that array (which can be done zerocopy, if the byte order in the file matches that of the host, but that must be checked at runtime), you can pass it safely into libopus.

This library is just a thin wrapper around xiph.org's libopus; I strongly recommend having a look at their API to understand the boundaries of responsibility of this codec. If it doesn't exist there, it probably shouldn't exist here. The links are in the README.

Best of luck!

**Comment by lherman-cs** [comment]
> I'm afraid this isn't true. int16 and float32 are explicitly an abstraction layer above bytes: they are an abstract concept, computers just happen to store them as bytes. What you are doing here is implicitly decoding a stream of bytes into a stream of ints. Note that the libopus API doesn't deal in bytes; it deals in int16s or float32s. How you get those is up to you; could be bytes, could be written on a piece of paper, could be JSON arrays directly parsed. Encoding and decoding a stream of int16s / float32s into bytes and back is up to you, the user.

This is exactly what I meant. int16 and float32 that are nothing but just byte array. So, the value itself can be treated as big/little endian, it's up to the user. For example, I can have a value stored in an int16 variable X (in big endian), but I can simply reorder the bytes in little endian and store it in the same int16 variable. From the library's perspective, you'll only see different values, which you may interpret it as big/little endian.

**Comment by hraban** [comment]
int16 and float32 are very explicitly not byte arrays. They are arrays of numbers. A valid implementation of a C abstract machine is one that doesn't use bytes at all, but e.g. 16-bit chars, in which int16s are stored 1-by-1.

Have a look at the opus docs: https://opus-codec.org/docs/opus_api-1.3.1/group__opus__encoder.html . You can see there PCM only coming in two flavours: int16, and float32. PCM is not bytes; PCM is an array of audio samples, that is, sequential air pressure measurements at high frequency (48KHz for example). None of that is about bytes: it's just numbers, and numbers don't need to be stored as bytes (and when they are, you need an explicit codec, like WAV).

For another example, see the web audio api: https://developer.mozilla.org/en-US/docs/Web/API/AudioBuffer/getChannelData . the output is a float32 array. You could encode this as e.g. JSON (not a good idea but bear with me), decode from JSON back into float32 in a server and pass directly to libopus, without ever touching a single byte [edit: explicitly. of course it's all bytes down under, but this about the explicit types.]

The  rule you're violating here is "strict aliasing". It's a common pitfall because "it just works" so often. Until it doesn't :) essentially, this is UB. See https://stackoverflow.com/questions/98650/what-is-the-strict-aliasing-rule for example for more info.

**Pull request closed without merging**
